project:
  type: website

website:
  title: "Emma Laura Schouten"
  search: false
  page-footer: 
      left:
          - "Copyright 2025, E.L. Schouten"
      border: true
  navbar:
      title: false
      logo: img/logo.png
      background: rgb(240, 238, 238)
      logo-alt: "Emma Laura Schouten"
      left:
        - href: index.qmd
          text: Over
        - href: pages/portfolio.qmd
          text: Portfolio
        - href: pages/pers.qmd
          text: Pers
        - href: pages/contact.qmd
          text: Contact

format:
  html:
    theme: 
        - cerulian
        - custom.scss
    mainfont: Nunito Sans
    #mainfont: "Arial"
    anchor-sections: false
    link-external-newwindow: true
    backgroundcolor: "#f7f7f7"

resources:
  - CNAME



